version: "3.8"

services:
  pen-app:
    build: ./pen-app
    container_name: pen-backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    volumes:
      - ./pen-app/app:/app
    networks:
      - pen-network

  pen-ui:
    build: ./pen-ui
    container_name: pen-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://pen-app:8000
    depends_on:
      - pen-app
    networks:
      - pen-network

networks:
  pen-network:
    driver: bridge
